parameters:
  twig.template.name: 'bootstrap'

  twig.paths:
    app:    '%kernel.directory.root%/templates/%twig.template.name%/app'
    common: '%kernel.directory.root%/templates/%twig.template.name%/common'
    layout: '%kernel.directory.root%/templates/%twig.template.name%/layout'
    macro:  '%kernel.directory.root%/templates/%twig.template.name%/macro'
    mail:   '%kernel.directory.root%/templates/%twig.template.name%/mail'

services:

  _defaults:
    autowire: true

  Twig\Loader\FilesystemLoader: ~

  Twig\Environment:
    arguments:
      $loader: '@Twig\Loader\FilesystemLoader'
      $options:
        cache: '%kernel.directory.cache%/%kernel.environment%/twig'
        debug: '%kernel.debug%'

  twig:
    alias: Twig\Environment
